// <auto-generated />
namespace Kinnect01Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change4));
        
        string IMigrationMetadata.Id
        {
            get { return "201804300550136_Change4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
